### ISSUE TITLE
Failed to activate the ide-haskell-hasktags package

### ISSUE THREAD

**Issue by jplatte** [atom-haskell/ide-haskell-hasktags#1]
Don't really know where this is coming from, I get this when opening a newly created cabal file (created by stack new).

**Atom Version**: 1.4.3
**System**: linux 4.3.3-3-ARCH
**Thrown From**: [ide-haskell-hasktags](https://github.com/atom-haskell/ide-haskell-hasktags) package, v0.0.1
### Stack Trace

Failed to activate the ide-haskell-hasktags package

```
At Cannot find module 'regex-cache'

Error: Cannot find module 'regex-cache'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/jplatte/.atom/packages/ide-haskell-hasktags/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/lib/utils.js:23:15)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/jplatte/.atom/packages/ide-haskell-hasktags/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/lib/expand.js:10:13)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/jplatte/.atom/packages/ide-haskell-hasktags/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/index.js:10:14)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/jplatte/.atom/packages/ide-haskell-hasktags/node_modules/chokidar/node_modules/anymatch/index.js:4:18)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/jplatte/.atom/packages/ide-haskell-hasktags/node_modules/chokidar/index.js:6:16)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/jplatte/.atom/packages/ide-haskell-hasktags/lib/tags.coffee:4:12)
    at Object.<anonymous> (/home/jplatte/.atom/packages/ide-haskell-hasktags/lib/tags.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/jplatte/.atom/packages/ide-haskell-hasktags/lib/ide-haskell-hasktags.coffee:2:8)
    at Object.<anonymous> (/home/jplatte/.atom/packages/ide-haskell-hasktags/lib/ide-haskell-hasktags.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:722:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:848:28
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (/usr/share/atom/resources/app.asar/src/package-manager.js:559:43)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:186:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.reloadGrammar (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:197:21)
    at new TokenizedBuffer (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:82:12)
    at new DisplayBuffer (/usr/share/atom/resources/app.asar/src/display-buffer.js:91:32)
    at new TextEditor (/usr/share/atom/resources/app.asar/src/text-editor.js:121:30)
    at Workspace.module.exports.Workspace.buildTextEditor (/usr/share/atom/resources/app.asar/src/workspace.js:587:14)
    at /usr/share/atom/resources/app.asar/src/workspace.js:563:24
    at process._tickCallback (node.js:368:9)
```
### Commands

```
     -2:59.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-pep8"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-cmake, v0.3.1
editorconfig, v1.2.4
haskell-ghc-mod, v1.6.6
ide-haskell, v1.3.9
ide-haskell-cabal, v1.0.0
ide-haskell-hasktags, v0.0.1
ide-haskell-repl, v0.0.17
language-autotools, v2.0.1
language-cmake, v0.1.4
language-haskell, v1.5.2
language-nginx, v0.6.1
language-rust, v0.4.5
linter, v1.11.3
linter-rust, v0.3.0
seti-icons, v0.4.5
seti-syntax, v0.4.1
seti-ui, v0.8.1
svg-preview, v0.7.3

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Seems like something got corrupted in Atom? Try to uninstall and then
reinstall this package.

**Comment by jplatte** [comment]
Yeah, that seems to have fixed it. How did you tell? (don't wanna create more issues on projects that are perfectly fine if this happens again)

**Comment by lierdakil** [comment]
Well, in this particular case I'm just reasonably familiar with code base, so I know that it doesn't use `'regex-cache'` module directly, so it's _probably_ an external problem. Then, if you look at stacktrace closely, you see that error is ultimately thrown from `/usr/share/atom/resources/app.asar/src/module-cache.js`, called by `/usr/share/atom/resources/app.asar/src/native-compile-cache.js`, on `require` no less. This is a sign that cache got corrupted for some reason.
