### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by edoardo90** [atom-haskell/ide-haskell-hasktags#2]
[Enter steps to reproduce below:]
1. save .hs file

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11
**Thrown From**: [ide-haskell-hasktags](https://github.com/atom-haskell/ide-haskell-hasktags) package, v0.0.1
### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at Tags.module.exports.Tags.update (/Users/edoardo/.atom/packages/ide-haskell-hasktags/lib/tags.coffee:37:9)
    at FSWatcher.<anonymous> (/Users/edoardo/.atom/packages/ide-haskell-hasktags/lib/tags.coffee:24:10)
    at emitTwo (events.js:87:13)
    at FSWatcher.emit (events.js:172:7)
    at FSWatcher.<anonymous> (/Users/edoardo/.atom/packages/ide-haskell-hasktags/node_modules/chokidar/index.js:171:15)
    at FSWatcher._emit (/Users/edoardo/.atom/packages/ide-haskell-hasktags/node_modules/chokidar/index.js:212:5)
    at FSWatcher.<anonymous> (/Users/edoardo/.atom/packages/ide-haskell-hasktags/node_modules/chokidar/lib/nodefs-handler.js:268:12)
    at /Users/edoardo/.atom/packages/ide-haskell-hasktags/node_modules/chokidar/lib/nodefs-handler.js:176:13
    at Array.forEach (native)
    at StatWatcher.<anonymous> (/Users/edoardo/.atom/packages/ide-haskell-hasktags/node_modules/chokidar/lib/nodefs-handler.js:175:31)
    at emitTwo (events.js:87:13)
    at StatWatcher.emit (events.js:172:7)
    at StatWatcher._handle.onchange (fs.js:1301:10)
```
### Commands

```
     -0:02.5.0 pane:show-previous-item (div.panels-item)
     -0:01.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "ide-haskell-hasktags": {
    "hasktagsPath": "/Users/edoardo/Library/Haskell/bin"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.6.2
coffee-compile, v0.21.1
coffee-navigator, v0.0.18
formatter-coffeescript, v0.1.1
haskell-ghc-mod, v1.6.6
ide-haskell, v1.3.9
ide-haskell-cabal, v1.0.0
ide-haskell-hasktags, v0.0.1
ide-haskell-repl, v0.0.17
language-haskell, v1.5.2
linter, v1.11.3
linter-coffee-variables, v0.4.2
linter-coffeescript, v1.0.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
`"hasktagsPath": "/Users/edoardo/Library/Haskell/bin/hasktags"`

**Comment by neu-rah** [comment]
then maybe "Hasktag Path" text should be "Hasktags File" or at least have a legend with an example

**Comment by lierdakil** [comment]
https://github.com/atom-haskell/ide-haskell-hasktags#configuration I think I articulated that well enough in readme.
