### ISSUE TITLE
Uncaught TypeError: target.getModel is not a function

### ISSUE THREAD

**Issue by peteryhwong** [atom-haskell/ide-haskell-hasktags#7]
[Enter steps to reproduce below:]

1. Open Haskell file (hs file)
2. Ensure the module type checks
3. Highlight a type (defined within the same module)
4. Right click and click 'Go to Declaration'

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [ide-haskell-hasktags](https://github.com/atom-haskell/ide-haskell-hasktags) package, v0.0.7

### Stack Trace

Uncaught TypeError: target.getModel is not a function

```
At $HOME/.atom/packages/ide-haskell-hasktags/lib/ide-haskell-hasktags.coffee:68

TypeError: target.getModel is not a function
    at atom-text-editor.upidisp.add.atom.commands.add.ide-haskell-hasktags:go-to-declaration ($HOME/.atom/packages/ide-haskell-hasktags/lib/ide-haskell-hasktags.coffee:68:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1181:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:02.9.0 core:save (input.hidden-input)
     -2:41.4.0 core:copy (input.hidden-input)
     -2:39.6.0 core:paste (input.hidden-input)
     -2:38.8.0 core:save (input.hidden-input)
     -2:36.9.0 core:move-right (input.hidden-input)
     -2:36.6.0 core:move-down (input.hidden-input)
     -2:36.3.0 core:move-up (input.hidden-input)
  2x -2:36.1.0 core:select-down (input.hidden-input)
  2x -2:35.6.0 core:backspace (input.hidden-input)
     -2:34.7.0 core:save (input.hidden-input)
     -2:20.4.0 ide-haskell-cabal:build (input.hidden-input)
     -2:10.4.0 ide-haskell-cabal:clean (input.hidden-input)
     -2:06.3.0 ide-haskell:toggle-output (input.hidden-input)
     -1:53.3.0 ide-haskell-cabal:build (input.hidden-input)
     -0:04.8.0 haskell-ghc-mod:go-to-declaration (div.scroll-view)
     -0:00.1.0 ide-haskell-hasktags:go-to-declaration (div.scroll-view)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "closeEmptyWindows": false,
    "projectHome": "$HOME/project",
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
agda-mode, v0.6.10 (inactive)
atom-cobol, v0.3.0 (active)
autocomplete-haskell, v0.7.1 (active)
haskell-ghc-mod, v1.19.6 (active)
ide-haskell, v1.9.1 (active)
ide-haskell-cabal, v1.7.4 (active)
ide-haskell-hasktags, v0.0.7 (active)
language-agda, v0.2.3 (active)
language-coq, v0.1.0 (active)
language-cspm, v1.1.0 (active)
language-docker, v1.1.7 (active)
language-groovy, v0.6.0 (active)
language-haskell, v1.10.4 (active)
language-maude, v0.3.0 (active)
linter, v1.11.21 (active)
linter-cspm, v1.3.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Let me guess... You used context menu to select 'go to declaration'? If so,
I know what the problem is, and will try to push fix later today. If not, I
will have to ask for more information. In any case, thanks for reporting.

вс, 5 февр. 2017 г., 13:22 Peter <notifications@github.com>:

**Comment by peteryhwong** [comment]
Yes, you are right 👍

**Comment by lierdakil** [comment]
Okay, v0.0.8 is out. Sorry about the hold-up.
